# Generated by Django 3.2.21 on 2023-10-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230924_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
        migrations.AddField(
            model_name='item',
            name='catalog',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lastOrderDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='lastReceivedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
