# Generated by Django 3.2.21 on 2023-11-09 21:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231029_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=api.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='api.status'),
        ),
    ]
