# Generated by Django 3.2.21 on 2023-12-05 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='quantity_requested',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='request_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
