# Generated by Django 3.2.21 on 2023-12-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20231205_1652'),
        ('api', '0006_auto_20231205_2152'),
    ]

    operations = [
    ]
